<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lesson05</RootNamespace>
    <AssemblyName>Lesson05.Starter</AssemblyName>
  </PropertyGroup>

</Project>
